# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check a deployment
  hosts: all
  vars:
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
    DCs:
      - redis
      - worker
      #      - centosmsg
      - pushgateway
      - nginx
  tasks:
    - set_fact:
        project_dir: "{{ playbook_dir }}/.."
      when: zuul is not defined
    - set_fact:
        project_dir: "{{ zuul.project.src_dir }}"
      when: zuul is defined
    - name: include variables
      include_vars: "{{ project_dir }}/deployment/roles/deploy/vars/{{ deployment }}.yml"

    - name: Checking running pods of {{ DCs }}
      include_tasks: check-pod-running.yml
      loop: "{{ DCs }}"
