---
- name: Build test image & run tests in container
  hosts: all
  tasks:
    - name: Install git and podman
      dnf:
        name:
          - git-core
          - podman
      become: true
    - name: Build dist2src container image
      command: make build
      args:
        chdir: "{{ zuul.project.src_dir }}"
      become: true
    - name: Run tests
      command: make check-in-container
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        COLOR: "no"
      become: true
