# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Build dist2src image
  hosts: all
  tasks:
    - name: Build dist2src image
      command: make build
      args:
        chdir: "{{ zuul.project.src_dir }}"
      become: true
