# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check deployment
  hosts: all
  tasks:
    - command: make check-deployment
      environment:
        DEPLOYMENT: dev
        ANSIBLE_STDOUT_CALLBACK: debug
      args:
        chdir: "{{ zuul.project.src_dir }}"
      become: true
